# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatDonations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grocery', models.IntegerField()),
                ('Meat', models.IntegerField()),
                ('Bread', models.IntegerField()),
                ('Produce', models.IntegerField()),
                ('Toiletries', models.IntegerField()),
                ('Diaper', models.IntegerField()),
                ('Other', models.IntegerField()),
                ('TotalPounds', models.IntegerField()),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerId', models.IntegerField(unique=True)),
                ('CustomerName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('donationID', models.IntegerField(primary_key=True, serialize=False)),
                ('donation_date', models.DateField()),
                ('comments', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrganizationName', models.CharField(max_length=100)),
                ('Salutation', models.CharField(max_length=100)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Comments', models.CharField(max_length=100)),
                ('StreetAddress', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Zip', models.CharField(max_length=100)),
                ('ICS', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GenericDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=100)),
                ('OrgName', models.CharField(max_length=100)),
                ('Contact', models.CharField(max_length=100)),
                ('FoodDesc', models.CharField(max_length=100)),
                ('Gallons', models.CharField(max_length=100)),
                ('avgCost', models.IntegerField()),
                ('totalCost', models.IntegerField()),
                ('GenDonation', models.CharField(max_length=1000)),
                ('Value', models.IntegerField()),
                ('ReceivedDate', models.DateField()),
                ('Comments', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='GOLF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Donation', models.CharField(max_length=1000)),
                ('Value', models.IntegerField()),
                ('Contact', models.CharField(max_length=100)),
                ('ReceivedBy', models.CharField(max_length=100)),
                ('donationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_tool.Donations')),
            ],
        ),
        migrations.CreateModel(
            name='InKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('isack_sent', models.BooleanField(default=False)),
                ('approxValue', models.IntegerField()),
                ('donationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_tool.Donations')),
            ],
        ),
        migrations.CreateModel(
            name='SearchDonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SearchQuery', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='donations',
            name='donor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_tool.Donors'),
        ),
        migrations.AddField(
            model_name='catdonations',
            name='donationID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_tool.Donations'),
        ),
    ]
