# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics_tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('donationID', models.IntegerField(primary_key=True, serialize=False)),
                ('donation_date', models.DateField()),
                ('additional_comments', models.CharField(max_length=100)),
                ('dontype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DonationsLog',
            fields=[
                ('logID', models.IntegerField(primary_key=True, serialize=False)),
                ('lastModifidDate', models.DateField()),
                ('lastChangedBy', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EBDGFOOD',
            fields=[
                ('EDBGEvent_foodID', models.IntegerField(primary_key=True, serialize=False)),
                ('ServingsPerGallon', models.IntegerField()),
                ('EBDGtype', models.CharField(max_length=20)),
                ('RestaurantName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EBDGRAFFLE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EMPTYBOWLFOOD',
            fields=[
                ('EmptyBowlEvent_foodID', models.IntegerField(primary_key=True, serialize=False)),
                ('food_description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('totalServings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EMPTYBOWLRAFFLEAUCTION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('receivedDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FOOD',
            fields=[
                ('foodEntryID', models.IntegerField(primary_key=True, serialize=False)),
                ('foodtype', models.CharField(max_length=100)),
                ('avgCost', models.IntegerField()),
                ('totalPounds', models.IntegerField()),
                ('totalValue', models.IntegerField()),
                ('NoPounds', models.IntegerField()),
                ('ServingsperPound', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FOODCATEGORY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryID', models.IntegerField()),
                ('donationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_tool.Donations')),
            ],
        ),
        migrations.CreateModel(
            name='FOODCATEGORYDESC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('categoryName', models.CharField(max_length=100)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_tool.FOODCATEGORY')),
            ],
        ),
        migrations.CreateModel(
            name='FOODENTRY',
            fields=[
                ('foodEntryID', models.IntegerField(primary_key=True, serialize=False)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_tool.FOODCATEGORY')),
            ],
        ),
        migrations.CreateModel(
            name='FUNDRAISINGEVENTS',
            fields=[
                ('eventID', models.IntegerField(primary_key=True, serialize=False)),
                ('estimatedValue', models.IntegerField()),
                ('receivedDate', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GOLF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtype', models.CharField(max_length=100)),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_tool.FUNDRAISINGEVENTS')),
            ],
        ),
        migrations.CreateModel(
            name='ITEMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('isack_sent', models.BooleanField(default=False)),
                ('approxValue', models.IntegerField()),
                ('donationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_tool.Donations')),
            ],
        ),
        migrations.CreateModel(
            name='MONETARY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('modeOfPayment', models.CharField(max_length=100)),
                ('donationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_tool.Donations')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('reportID', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=100)),
                ('reportgen_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEvents',
            fields=[
                ('service_detailID', models.IntegerField(primary_key=True, serialize=False)),
                ('date_of_service', models.DateField()),
                ('serviceID', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='emptybowlraffleauction',
            name='eventID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_tool.FUNDRAISINGEVENTS'),
        ),
        migrations.AddField(
            model_name='ebdgraffle',
            name='eventID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ics_tool.FUNDRAISINGEVENTS'),
        ),
    ]
