# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ics_tool', '0001_initial'),
    ]

    operations = [
        
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(max_length=255)),
            ],
        ),
       
    ]
